### ISSUE TITLE
Show answers sorted by number of upvotes in the left navigation bar

### ISSUE THREAD

**Issue by kanihal** [AnthoPakPak/StackOverflowPowerUser#1]
<img width="572" alt="2020-10-07_18-52-46" src="https://user-images.githubusercontent.com/7579686/95336888-d254f380-08ce-11eb-9079-b4e86563faab.png">

The left navigation doesn't show the most upvoted answer on a page. 
For example, At https://stackoverflow.com/questions/3810521/how-to-install-python-distutils, there is an answer with 195+ upvotes, but not showing up in the left bar.

If the items on the left navigation bar are sorted by 'Number of upvotes', I think it would help us reach the most appropriate answers faster.

**Comment by AnthoPakPak** [comment]
The sort order here is the same as the one you've chosen for answers. I see you have ticked "Oldest" and this is why you get this unsorted order. I'd advise to tick Votes instead which will give you expected sorting.
