### ISSUE TITLE
[Suggestion] Percent Styling

### ISSUE THREAD

**Issue by ryanbuening** [AnthoPakPak/StackOverflowPowerUser#2]
Great extension! Not an issue, but a possible improvement idea could be to match StackOverflow's upvote/downvote font (Arial) and colors which are #76C490 and #D25D5D.

An option to hide the percent when it is 100% might be nice as most answers fall into that category and it's just noise. You really want to highlight the answers with a lot of downvotes/lower percent.

The images below use the following styles.

**Green**
font-family: Arial;
color: #76C490;
font-size: 21px;

![image](https://user-images.githubusercontent.com/812974/108005215-1d41ee80-6fc6-11eb-8bee-a9adf0757b56.png)

**Red**
font-family: Arial;
color: #D25D5D;
font-size: 21px;

![image](https://user-images.githubusercontent.com/812974/108005210-1915d100-6fc6-11eb-8fa1-9cabd7863cc1.png)

**Comment by marcelgarus** [comment]
I would really appreciate this.

Until now, I installed a CSS editing extension only for hiding the percentage, because the green circle was so distracting.

**Comment by AnthoPakPak** [comment]
Hey guys,

Sorry for this late answer, had busy times recently.

I'll try to improve the style of the percentage, mainly the circle. I do agree it can be quite distracting. But keep in mind that the background color comes as an indicator of the quality of the answer. It's not just green or red. [It's a variant from green to red according to answer quality percentage](https://github.com/AnthoPakPak/StackOverflowPowerUser/blob/master/js/features/expand_votes_counts.js#L155).

What I'll check first is that if using only colored text (without circle background) is sufficient. This wasn't an option before, but now with dark mode on SO it may be readable :)

**Comment by AnthoPakPak** [comment]
I've worked on this, it will be available in the next update, which you can expect soon.

I'm fetching green/red colors of up/down votes on SO (which is different when using light/dark mode), and use them for the percent styling.
As I've explained earlier, the percent color isn't just green or red, it's a value from a gradient between the two colors. 80% is considered a sufficiently bad answer, so anything below 80% will be red. 100% is green. % between 80 and 100 have a color from the gradient, depending on the value.

Here's the result with those new colors:
<img width="774" alt="Capture d’écran 2021-08-10 à 13 13 00" src="https://user-images.githubusercontent.com/16854916/128858396-ec3fc0f0-c77a-4d73-9344-7b0cc3a4d2c0.png">
<img width="746" alt="Capture d’écran 2021-08-10 à 13 11 40" src="https://user-images.githubusercontent.com/16854916/128858410-1b278499-97dd-4602-ae7e-4dbfba56166e.png">
<img width="761" alt="Capture d’écran 2021-08-10 à 13 11 56" src="https://user-images.githubusercontent.com/16854916/128858417-90f64d55-a345-42bd-942e-125bcaae8f95.png">

**Comment by AnthoPakPak** [comment]
Changes are available on version 0.3.5 (which has just been submitted).
