### ISSUE TITLE
Hide "featured on meta" and the overflow blog/podcast

### ISSUE THREAD

**Issue by CodingDive** [AnthoPakPak/StackOverflowPowerUser#5]
Hey! Thank you so much for all the work on this amazing extension.

I have the  option `Hide the "Featured on Meta" & "Hot Meta posts" block from right sidebar` enabled, yet I still see "featured on meta" and some ads for their overflow blog/podcast. Is there a way to disable all of it so that the sidebar shows only `linked` and `related` posts?

![image](https://user-images.githubusercontent.com/28842311/130767211-7ab29f47-e947-43fd-a692-ed96e1382d02.png)

**Comment by AnthoPakPak** [comment]
This feature was broken because of DOM change. I've updated it and just submitted the update to the store. Should be available soon!
