### ISSUE TITLE
Site width

### ISSUE THREAD

**Issue by btxtiger** [AnthoPakPak/StackOverflowPowerUser#8]
Can you add an option to change max-width of the content? E.g. I personally prefer to have 1400px width, makes the code much better readable. The width of 60/80 characters is really outdated.
You need to adjust max-width at `body>.container` and `div#content`

![image](https://user-images.githubusercontent.com/15804690/213087624-028a2049-b33f-4d9f-bc6e-9e4809794fc9.png)

**Comment by AnthoPakPak** [comment]
There's an ongoing PR (#7) for this that I still need to review before merging. It'll need some changes that I didn't had time to do yet, but I'll try to priorise this.

**Comment by AnthoPakPak** [comment]
Completed in 0.4.2 version which will soon be available on the Chrome store!

**Comment by jonaaix** [comment]
Hi, tested it and it works fine.
However 80% on 13 inch macbook is totally different than 80% on 27 inch 4k display. So it should be possible to limit it by pixels. Also the left sidebar should be kept in the middle. If you use ultra-wide screens it will move far away from the center.

<img width="1505" alt="image" src="https://user-images.githubusercontent.com/15804690/214276122-3348d4de-ff79-4e14-b3d7-36e230f81820.png">

**Comment by AnthoPakPak** [comment]
Yeah I agree we could also add a setting to limit to a max amount of pixels to better support switching between different resolutions. Feel free to experiment and make a PR for this if it's something you really need.
About the sidebar, are you referring to the extension one or the SO one? I don't see any issue with the sidebar on your screenshot.
